### ISSUE TITLE
It is possible to create blocks receive ObjCInstance argument?

### ISSUE THREAD

**Issue by eminarcissus** [beeware/rubicon-objc#131]
For instance, if I would like to create a block to receive UIGestureRecognizer  instance, I create a method like this.

def handle_gesture(gesture: ObjCInstance) -> None:
    print(gesture)

view.addCustomGesture(UITapGestureController.alloc().initWithHandler(handle_gesture))
it looks like it does create the gesture correctly, but the callback didn't being called.

I know I can use the vanilla selector in together with addGesture method, but I would like to know if it is possible to create block callbacks receive a ObjCInstance and handle in python side. I've taken a look at the test folder, it did include a few tests of type of (int,int), but didn't find any information about how does block running process went like here(including the gc part of python instance relate to block etc.)

Any help would be real appreciated :)

**Comment by eminarcissus** [comment]
Thanks for the help.

Yes, this is the signature line created by Xcode(code was originally written with Swift, I use @objc to export to objc namespace)

(nonnull instancetype)initWithAddToView:(UIView * _Nonnull)targetView closure:(void (^ _Nonnull)(UIGestureRecognizer * _Nonnull))closure;

so gesture can be called like this
UITapGestureRecognizer.alloc().initWithAddToView_closure_(self.view,handler_block)

After register the gesture, python part didn't raise any error out, and when doing the tap event, it didn't raise any error but the callback is not being called. For the detailed source code, this is the code https://gist.github.com/JohnCoates/2b6892b023a3f93092ab395cb8b743c9,
I've modified it a little bit and add initWithAddToView with a @objc decorator to make it exposed to objc namespace.

**Comment by eminarcissus** [comment]
Two more questions here if it won't bothers.
1: How to define class method?(does @class_method works here?)
2: Sometimes override method won't work here.
For problem 2 it looks quite complicated to describe, I have a class named ModalView, which is extended from UIView, it calls render(self) in the init progress, after I exposed this method with @objc and trying to override this method, I found the overwritten one doesn't being called at all. I tried couple a few other cases here(a swift defined class, inherits from a either a UIViewController or UIView or something exposed to objc namespace), functions dedicated to swift defined class, override is not working at all somehow, so I guess it does have something to do with swift/objc bridge, not something caused by python bridge, so don't know if question post here is appropriate or not :)

**Comment by dgelessus** [comment]
Hm, strange, I really don't see anything wrong with the method call (or with the declaration).

Just for testing, could you change your `init(addToView:closure:)` method to make it call `closure` immediately, instead of adding it as a gesture action? That would make it easier to test (you don't have to tap anymore) and it would narrow down the problem (we can see if UIKit or the custom gesture handling code has anything to do with it).

> How to define class method?(does `@class_method` works here?)

No, `@classmethod` doesn't work. To create an Objective-C class method with Rubicon, you need to use `@objc_classmethod` instead of `@objc_method`.

> after I exposed this method with `@objc` and trying to override this method, I found the overwritten one doesn't being called at all.

That's not possible - if you define a class in Swift, you cannot subclass it in Objective-C (see [Stack Overflow](https://stackoverflow.com/q/24204211) and [Apple's Objective-C to Swift migration guide](https://developer.apple.com/documentation/swift/migrating_your_objective_c_code_to_swift#2993716)). If you tried this in normal Objective-C code, you'd get a compiler error: in the generated Objective-C headers, all Swift classes are [marked](https://github.com/apple/swift/blob/be693bba82857e7c26842b46ca58be085a181a76/lib/PrintAsObjC/PrintAsObjC.cpp#L2561-L2563) with `__attribute__((objc_subclassing_restricted))`, which prevents subclassing them in Objective-C. This is only checked by the compiler, not by the Objective-C runtime, which is why you don't get any errors when you subclass a Swift class using Rubicon. But since you're doing something that is normally prevented by the compiler, it's not guaranteed to work as you'd expect.

**Comment by freakboy3742** [comment]
If I'm reading this right, this isn't a bug in Rubicon; it's either a mistake of usage, or perhaps an issue with the Swift bridge. On that basis, I'm going to close this ticket; if you think there's something here that still needs to be resolved, let us know and we can re-open.
