### ISSUE TITLE
Possible memory leak in async handler on Cocoa?

### ISSUE THREAD

**Issue by SamSchott** [beeware/rubicon-objc#146]
## Current Behavior
When having an async task running in regular intervals, for instance to update a GUI according to some underlying state, the memory usage slowly but steadily increases. This is the case even if the async task does not actually do anything.

If this is indeed a bug, maybe it is better filed with rubicon.

## Steps to reproduce
Here is a minimum example of a callback which runs a periodic background task (`pass`) ever 0.1 sec. The app's memory usage steadily increases by 0.1 MB every ~ 5 sec. If you leave it running for 8h without the PC going to sleep, memory usage will increase by ~ 140 MB.

```python
import toga
from toga.constants import CENTER
from toga.style import Pack


class ExampleApp(toga.App):

    def startup(self):

        self.button = toga.Button(
            label='Start updates',
            style=Pack(padding=10, width=100),
            on_press=self.update_label
        )

        self.label = toga.Label(
            text='----',
            style=Pack(padding=10, width=100),
        )

        self.box = toga.Box(
            children=[self.button, self.label],
            style=Pack(alignment=CENTER, flex=1)
        )

        self.main_window = toga.MainWindow()
        self.main_window.content = self.box
        self.main_window.show()


    def update_label(self, sender, interval=0.1):
        self.label.text = 'Updating...'
        while True:
            yield interval


def main():
    return ExampleApp('Example App', 'org.beeware.app.example')


if __name__ == '__main__':
    main().main_loop()
```

## Your Environment

* Python Version: 3.7.6
* Operating System and Version: macOS 10.15.2
* Toga Version: current master branch (v0.3.0.dev18)
* Toga Target: cocoa

**Comment by SamSchott** [comment]
Looking at the output of tracemalloc, this may be related to instances of `CFRunLoopTimerCallBack` being created but not collected. But this is just a shot in the dark...

**Comment by dgelessus** [comment]
After poking around a little with a debugger, I'm fairly sure it's related to this:

https://github.com/beeware/rubicon-objc/blob/8f879544b2919d682ddf74058f023c2c1672875d/rubicon/objc/eventloop.py#L159

Every time the Toga callback `yield`s, a `CFTimerHandle` is created internally. `CFTimerHandle.__init__` adds the newly created `self` to a set (`self._loop._timers`), but `self` is never removed from that set again, until either the event loop is closed or `CFTimerHandle.cancel` is called. Neither of these things happen during normal execution, so the loop's `_timers` set keeps growing slowly, which seems to be where the memory usage comes from.

Unfortunately I don't know very much about rubicon-objc's `asyncio` integration (or about `asyncio` in general), so I don't know what should be done to fix this.

**Comment by freakboy3742** [comment]
@dgelessus Thanks for that debug assistance - it's most helpful. I think that should be enough to for me to find a way to plug the leak.

**Comment by SamSchott** [comment]
I have looked into this a little and adding `self._loop._timers.discard(self)` after `callback(*args)` in `cf_timer_callback` does eventually result in the `CFTimerHandle` instances being garbage collected:

https://github.com/beeware/rubicon-objc/blob/8f879544b2919d682ddf74058f023c2c1672875d/rubicon/objc/eventloop.py#L141-L145

However, the memory usage still increases for some reason, albeit slower. It is noticeable when setting the callback interval to 0.01 sec with an increase of memory usage by maybe 50 kB / sec. Manually triggering garbage collection after `self._loop._timers.discard(self)` seems to get rid of this, so maybe this is a memory fragmentation issue when instances are garbage collected later?

**Comment by freakboy3742** [comment]
If a manual GC run results in no overall leak, that would seem to suggest that the fix you're proposing is sufficient; it's just waiting on the garbage collector to fire. 

Python's garbage collector is based on reference counting; the downside to that approach is that circular references take a little longer to be freed. If a reference count would cause an object to be garbage collected, but there are still references, it's moved to a "second generation" of objects; if garbage collection gets triggered a second time, and the object still has references, it moves to a third generation. Python has a threshold on the size of the second and third generation; when the interpreter hits that threshood, objects in that generation are evaluated (and, if possible, freed).

If, instead of calling `gc.collect()` to trigger garbage collection, you invoke `gc.get_count()`, you'll see the population of each generation. If you let the process run for a while, you'll see the second and third generation counts increase; but once you hit the threshold count (10 by default), the garbage collector kicks in, and a big block of memory is freed.

This does mean that that *peak* memory requirement is higher - but it's a lot less than you see with an outright leak.

So - my read is that the patch you suggest (adding the discard) is correct. There might be a cleaner version that avoids the circular reference in the first place, but it's not immediately obvious to me what that would be.

**Comment by SamSchott** [comment]
Good to know, thanks for the info. I agree, it would be better to avoid circular references in the first place. But this was the easiest fix :)
