### ISSUE TITLE
Documentation builds on Read the Docs are failing

### ISSUE THREAD

**Issue by dgelessus** [beeware/rubicon-objc#149]
Example: https://readthedocs.org/projects/rubicon-objc/builds/10447164/

The problem appears to be that Read the Docs is trying to build the docs using Python 2.7. This won't work, because Rubicon requires at least Python 3.5.

Also, the build seems to be installing a hardcoded list of requirements for the doc build, rather than using the [docs/requirements_docs.txt](https://github.com/beeware/rubicon-objc/blob/master/docs/requirements_docs.txt) from our repo.

I haven't used Read the Docs before, so I don't know what determines the commands that it uses to build the docs. Is there a configuration page somewhere that I don't know about/don't have access to? Or does it just default to this specific set of commands for all projects?

**Comment by freakboy3742** [comment]
/me grumbles.

Read The Docs has rolled out some configuration changes over the last few months, partly to introduce some new features, and partly to move to preferring Python 3 over Python 2.7. Historically, there hasn't been any way to get notifications when builds fail; however, I now see that they've added *that* feature too.

Turns out the fix here was relatively straightforward; I've made the change, and the docs are now live.

There *is* a GUI that configures the build (although some aspects of that configuration have recently been exposed as a configuration file). I'm happy to give you access to Rubicon's config; set up and account on ReadTheDocs.org and let me know your details.

**Comment by dgelessus** [comment]
Thanks for the quick fix! It's building successfully now: https://readthedocs.org/projects/rubicon-objc/builds/10449102/

I'm now registered on readthedocs.org as dgelessus (and linked to my GitHub account, if it matters), so feel free to add me to the project.
