### ISSUE TITLE
ObjCBlock For bounded methods

### ISSUE THREAD

**Issue by arandomdev** [beeware/rubicon-objc#153]
I'm having trouble using a bounded method as a block, for example, running this

```
class A(object):

	def __init__(self):
		handler = objc.Block(self.handler)

	def handler(self) -> None:
		pass

A()
```
gives the following exception,
`ValueError: Block callables must be fully annotated or explicit argument types must be specified.`

Is there a way to annotate the "self" argument?

**Comment by dgelessus** [comment]
Can confirm that I get the same error using the example code you provided.

This looks like a bug in rubicon-objc. There *should* be no need to annotate the `self` parameter here, because you're passing in `self.handler` and not `A.handler`, so `self` is set to a fixed value and not passed in from Objective-C.

As a workaround I was going to suggest setting the return type explicitly (using `objc.Block(self.handler, None)`) so that Rubicon doesn't need to read the return/argument types from the function annotations. But it turns out that triggers *another* bug - when you pass `objc.Block` only a return type and no argument types (because the method doesn't take any arguments), Rubicon thinks that the argument types are missing, so it tries to read the parameter annotations anyway, which triggers the original issue again.

As a *different* workaround for now, until these two bugs are fixed, you can use something like this:

```python
def __init__(self):
    def _block() -> None:
        self.handler()
    handler = objc.Block(_block)
```

or a slightly shorter version:

```python
def __init__(self):
    handler = objc.Block(lambda: self.handler(), None)
```

This wraps the method in a regular function, which "hides" the `self` parameter from Rubicon, so that it doesn't complain about missing annotations.

Thank you for the bug report!

**Comment by arandomdev** [comment]
Thank you so much, your suggestion worked perfectly. I was afraid I would have to convert back and forth between objc_util.
