### ISSUE TITLE
NSTableView

### ISSUE THREAD

**Issue by mischievous** [beeware/rubicon-objc#199]
I was looking at switch overing to rubicon-objc from pyobjc, but before I spend all the time changing my code around I wanted to ask a simple question.  

In pyobjc I can't subclass (or make a category) an have NSTableView work correctly unless I also set the tableview delegate back to itself.  

For grins and giggles I reproduced what I was doing in an actual xcode project.  I can subcalss the NSTableView and it works correctly.  I can use objc categories on the NSTableView and it works correctly.  

Specifically I want to catch these calls "-(NSView *)makeViewWithIdentifier:(NSUserInterfaceItemIdentifier)identifier owner:(id)owner".

I was looking at rubicon and toga.   It appears that toga is also setting the NSTableView delegate back to TogaTable (subclass of NSTableView) instance.  

1) Is this required for Toga to work correctly for Toga sake?. Or is this because NSTableView will not work correctly with a python subclass on NSTableView?
    a) Is there an example that uses TogaTable? 

2) Does rubicon support obj-c categories?  

Thank you,
Alexandra

**Comment by freakboy3742** [comment]
The setup in Toga is more of a convenience than anything else. In the cast of Table, we don't gain anything by having a delegate class independent of the widget class, so we haven't separated the two. However, there are other widgets (for example, OptionContainer) that instantiates an NSTabView, but uses a separate class instance (TogaTabViewDelegate) as the delegate. I can't think of any reason that you wouldn't be able to split the usage of NSTableView in the same way. 

As for an example of TogaTable - the examples folder in the Toga repository contains table and table_source demos, both of which show off Table usage. That demo is a level higher abstraction than TogaTable (it uses the platform independent API, rather than the Cocoa implementation API), but it's calling the TogaTable (and thus the cocoa NSTableView) at the end of the day.

Categories are an interesting case. As I understand it, they are entirely a language-level feature. I don't believe they have any manifestation in the Objective C *runtime*; they're purely a way for the Objective C compiler to do type checking. At runtime, they're an ordinary NSObject that receives messages - which is how Rubicon interacts with them. As a result, you can override `makeViewWithIdentifier:owner:` by defining:

```
class MyDelegate(NSObject):
    ...
    @objc_method
    def makeViewWithIdentifier_owner_(self, identifier, owner):
        ...
```

This relies on the fact that any un-annotated argument in Rubicon is interpreted as an NSObject, and the default return type is NSObject as well.

Since I *think* I've answered your question, I'm going to close this ticket for procedural reasons; but if need any follow up details, please don't hesitate to continue the discussion here, or on a new ticket.
