### ISSUE TITLE
Pyto with Objective-C for IOS

### ISSUE THREAD

**Issue by nsmith1024** [beeware/rubicon-objc#212]
Hello,

I have existing objective-C IOS app, and i would like to add python to it by using  Pyto Python (which uses rubicon) with it to create one executable containing my original xcode objective-c IOS app, plus the Pyto Python interpreter.

https://pyto.app/

I have 2 questions

1. Can I integrate Pyto Python with my existing Objective-C IOS app to create a single executable containing the Pyto Python interpreter and objective-c, where objective-c will start running when the app launches??

2. After doing (1) above, can I then call Pyto Python scripts from Objective-C functions using rubico?

I read the docs on rubico  but it only shows how to call objective-c from python, not the other way around, calling python from objective-c

Thanks

**Comment by dgelessus** [comment]
Hi! I'm not very familar with Pyto, sorry - if you have questions about using Pyto in your own iOS app, it would be better if you ask the Pyto developer directly.

That said - if you just need a Python runtime and not Pyto specifically, you can try using the BeeWare [Python Apple support package](https://github.com/beeware/Python-Apple-support). It lets you build Python in a way that can be embedded in an iOS/tvOS/watchOS app. This won't include any of the libraries that Pyto comes with, so you would need to manually add all libraries you need (such as rubicon-objc).

Regarding calling Python code from Objective-C, there are multiple steps to this. First you need to start Python itself and load the Python code that you want to access. You can see how this is done in [our iOS Python app template](https://github.com/beeware/briefcase-iOS-Xcode-template/blob/dev/%7B%7B%20cookiecutter.formal_name%20%7D%7D/%7B%7B%20cookiecutter.app_name%20%7D%7D/main.m). That template is meant for apps where the main part is written in Python, so once it has finished loading, it tries to run the app with a `PythonAppDelegate` defined by the Python code. You would need to change this for your app so that it uses your existing Objective-C app delegate instead.

Once you have that set up, you need to define an Objective-C object on the Python side and pass it to the Objective-C code. The easiest way is probably to make a property for it on your app delegate and have your Python code store it there. You also need to define a protocol on the Objective-C side that will be implemented by the Python object, so that the Objective-C compiler knows the method types of the Python-defined object. For example:

```objc
@protocol PythonInterface
-(int)someMethod:(int)arg;
@end

// and in your app delegate
@property(strong) id<PythonInterface> pythonInterface;
```

And in your Python code:

```python
PythonInterface = ObjCProtocol("PythonInterface")
class PythonInterfaceImpl(NSObject, protocols=[PythonInterface]):
    @objc_method
    def someMethod(x: int) -> int:
        return 2 * x

UIApplication = ObjCClass("UIApplication")
UIApplication.sharedApplication.delegate.pythonInterface = PythonInterfaceImpl()
```

Then you should be able to call e. g. `[self.pythonInterface someMethod:123]` in your Objective-C code.

**Comment by freakboy3742** [comment]
It's also worth noting that Pyto bakes in an old (pre v0.4 IIRC) version of Rubicon, so recent API changes may not be available if you use Pyto as the base for your app.

**Comment by nsmith1024** [comment]
Thanks so much for both your responses i really appreciate it!

**Comment by freakboy3742** [comment]
Closing on the basis that the original question appears to be answered.
