### ISSUE TITLE
Scroll blocks eventloop for ios

### ISSUE THREAD

**Issue by alibeyram** [beeware/rubicon-objc#316]
### Describe the bug

We noticed that the event loop blocks when you scroll. This is similar to [issue 228](https://github.com/beeware/rubicon-objc/issues/228)

### Steps to reproduce

1. Create a 2-page linked positron-static demo (you can use my fork example [here](https://github.com/alibeyram/toga/tree/main/examples/positron-static) )
2. Scroll down before clicking to the second page and you should see that it does not work.

if you use Safari Develop > Simulator to inspect the WebView you would see a timeout error.

### Expected behavior

Scrolling should not impact the clicking behavior

### Environment

- Operating System: iOS (16.4)
- Python version: 3.10
- Software versions:
  - Briefcase: 0.3.14
  - Toga: 0.3.1
  - rubicon-objc: 0.4.6

### Additional context

The workaround in [issue 228](https://github.com/beeware/rubicon-objc/issues/228) also solves this problem.

```python
async def heartbeat(*args, **kwargs):
    while True:
        await asyncio.sleep(0.1)
self.add_background_task(heartbeat)
```

**Comment by freakboy3742** [comment]
Thanks for the report. One additional detail that will help here - what version of *Rubicon* are you using?

**Comment by alibeyram** [comment]
@freakboy3742 updated it in the issue.

**Comment by landrybr** [comment]
I think the problem is that `CFRunLoopRun` runs the run loop exclusively in its default mode.  It seems that if the thread switches to another mode, for example `UITrackingRunLoopMode` when the user scrolls, then `CFRunLoopRun` gets terminated.  I think the way to fix this is to replace `CFRunLoopRun` with calling `run` from the current `NSRunLoop` which can handle switching modes.  This fixes the problem in the example code.  PR here: https://github.com/beeware/rubicon-objc/pull/317
