### ISSUE TITLE
"ImportError: No module named 'rubicon'" if trying to bundle script via py2app.

### ISSUE THREAD

**Issue by frypf** [beeware/rubicon-objc#347]
### Describe the bug

I've installed the [desktop-notifier](https://github.com/samschott/desktop-notifier) package which uses rubicon-objc as a dependency. I've followed the [basic instructions on setting up a CFRunLoop](https://github.com/samschott/desktop-notifier#event-loop-integration) supplied there and I can successfully get python to send configurable desktop notifications and execute their callbacks.

Unfortunately, if I try to integrate my working code into an application bundled via py2app, I get the error as indicated in the title. (If I build the app in alias mode there is no issue, but with either standalone or semi-standalone, the app fails to build). Specifically, it appears as though it can't resolve the module when I use `from rubicon.objc.eventloop import EventLoopPolicy`.

I've even subsequently reinstalled both desktop-notifier & rubicon-objc universally, but still get the same error, while the python code itself imports correctly when run directly. Could either be an idiosyncracy with how py2app handles external dependencies, (although I've used it in the past for a couple of scripts and they compiled without issue), or maybe I'm overlooking something obvious. Any help would be greatly appreciated though thank you 🙏.

### Steps to reproduce

1) Include `from rubicon.objc.eventloop import EventLoopPolicy` in a python script.
2) Attempt to bundle it into an app using [py2app](https://github.com/ronaldoussoren/py2app) (simplest way is run `py2applet /path/to/script.py` from a terminal).

### Expected behavior

The app should build.

### Environment

- Operating System: macos 12.5.1
- Python version: 3.11.4 (installed via homebrew)

**Comment by freakboy3742** [comment]
Thanks for the report; however, it's not clear to me that this is a bug in Rubicon. `No module named Rubicon` suggests that py2app isn't packaging the requirement correctly. I know nothing about py2app configuration, so I can't really advise on what you might have done wrong. The py2app support channels might be a better source of help.

I'm going to close this ticket for now; however, if it turns out that Rubicon *is* doing something wrong, let us know and I'll be happy to re-open this ticket.
