### ISSUE TITLE
Duplicate elements in repr of `ObjCInstance`

### ISSUE THREAD

**Issue by qqfunc** [beeware/rubicon-objc#432]
### What is the problem or limitation you are having?

The repr of `ObjCInstance` is as follows:
```
<rubicon.objc.api.ObjCInstance (id): (class name) at (address): (debugDescription)>
```

For example:
```
<rubicon.objc.api.ObjCInstance 0x104d0f690: NSObject at 0x6000031a8050: <NSObject: 0x6000031a8050>>
```

The class name and address parts are duplicated because `NSObject.debugDescription` also contains them.
I think this may be a little long.

### Describe the solution you'd like

```
<rubicon.objc.api.ObjCInstance (id): (class name) at (address)>
```
```
<rubicon.objc.api.ObjCInstance 0x104d0f690: NSObject at 0x6000031a8050>
```
In this form, `NSObject.debugDescription` is omitted.

### Describe alternatives you've considered

```
<rubicon.objc.api.ObjCInstance (id): (debugDescription)>
```
```
<rubicon.objc.api.ObjCInstance 0x104d0f690: <NSObject: 0x6000031a8050>>
```
This time, `(class name) at (address)` is omitted.

**Comment by freakboy3742** [comment]
No objection to tweaking the representation of `ObjCInstance`. 

However, I'd be inclined to take your "alternate" representation, preserving `debugDescription` rather than the `(class name) at (address)` portion. The default fallback representation of `debugDescription` has the same detail as `(class name) at (address)`; but if the class has a useful debug representation (e.g., NSURL returns the actual URL), you'll see that instead - `<rubicon.objc.api.ObjCInstance 0x1064c4a00: https://beeware.org>` - which is more useful as a debug representation.

**Comment by qqfunc** [comment]
Indeed, that seems to make sense. Then, there might be also the following ways:

1. Check if the `debugDescription` is like `<(class name): (address)>`. If so, the class name and address is represented. Otherwise, the `debugDescription` is used.
- NSObject:
```
<rubicon.objc.api.ObjCInstance (id): NSObject at (address)>
```
- NSURL:
```
<rubicon.objc.api.ObjCInstance (id): https://beeware.org/>
```

2. Similar to 1, but **the same way as now** is used if the `debugDescription` is not like `<(class name): (address)>`. 
- NSObject:
```
<rubicon.objc.api.ObjCInstance (id): NSObject at (address)>
```
- NSURL:
```
<rubicon.objc.api.ObjCInstance (id): NSURL at (address): https://beeware.org/>
```
This way, class names are not lost in case of `NSURL`.

3. Implement `ObjCURLInstance` and so on. It may be hard.

**Comment by freakboy3742** [comment]
Honestly - I don't think it's worth massively optimising the output representation and introspecting looking for specific output types. It's a debug representation. It's not meant to be a form that is surfaced to the user. That's why I'm not especially concerned about the current duplication - the "long" form that is currently output isn't ambiguous, and requires no special handling. 

However, if we are going to optimise, I agree the ObjC class name is a good thing to retain; my inclination would be to keep it simple, and return:

    <ObjCInstance:(class name) (id): (debugDescription)>

That is - drop the full class path for ObjCInstance, use the ObjC class name, the Python id, and the ObjC debug description. This would yield:

    <ObjCInstance:NSObject 0x104d0f690: <NSObject: 0x6000031a8050>

for the NSObject case, and:

    <ObjCInstance:NSURL 0x104d0f690: https://beeware.org>

for the NSURL case. I could even be convinced to go further, and introduce a shorthand for "ObjCInstance":

    <@(class name) (id): (debugDescription)>

After all - there's nothing gained by giving the full Rubicon class name - we just need to signal in debug output that we're dealing with an ObjC instance. A single character like `@` can signal that just as well as `rubicon.objc.api.ObjCInstance`.

**Comment by qqfunc** [comment]
If the full class path is no longer needed, the representations of the other classes may be helpful.
I checked the code and the representations are now like this:

| Class name | Representation |
| --- | --- |
| `ObjCMethod` | `<ObjCMethod (name) (encoding)>` |
| `ObjCPartialMethod` | `<rubicon.objc.api.ObjCPartialMethod (partial name)>`
| `ObjCBoundMethod` | `rubicon.objc.api.ObjCBoundMethod(<ObjCMethod ...>, (receiver))`
| `ObjCInstance` | `<rubicon.objc.api.ObjCInstance (id): (class name) at (address): (debugDescription)>` |
| `ObjCClass` | `<rubicon.objc.api.ObjCClass: (class name) at (address)` |
| `ObjCProtocol` | `<rubicon.objc.api.ObjCProtocol: (protocol name) at (address)` |
| `ObjCBlock` | `<ObjCBlock@address>` |
| `Block` | default (`<rubicon.objc.api.Block object at (id)>`) |

Only `ObjCMethod` and `ObjCBlock` don't have the `rubicon.objc.api.` part. Unifying them might be worthwhile, but in the case of using `@`, the unification should be done in a different way. The way which uses `@` is a bit unusual, but it's also fascinating.

**Comment by freakboy3742** [comment]
Agreed that we could tighten the representations (dropping at least the class path) for these other types as well. There's some other tweaks that could probably be dropped as well - for example, there's no need for the `id` on the Class and Protocol output (since each class and protocol can only be defined once)

I'm not sure how `@` notation would fit into those; it's a convenient shorthand for *one* class repr, but I'm not sure we'd be able to use it for more than one.

So - we could either say that ObjCInstance is the most commonly used class, and make it a special case with a very short shorthand; or we could drop that idea entirely and just use `ObjCInstance:NSObject`. I do wonder if the `@` is a little *too* smart, and we should just stick to the longer form, even if it is longer.

**Comment by qqfunc** [comment]
Then the changes would be as follows for now:

| Class name | Representation |
| --- | --- |
| `ObjCPartialMethod` | `<ObjCPartialMethod (partial name)>` |
| `ObjCBoundMethod` | `ObjCBoundMethod(<ObjCMethod ...>, (receiver))` |
| `ObjCInstance` | `<ObjCInstance:(class name) (id): (debugDescription)>` |
| `ObjCClass` | `<ObjCClass: (class name)>` |
| `ObjCProtocol` | `<ObjCProtocol: (protocol name)>` |

- Show only class names, not class paths
- Delete the pointer addresses from `ObjCClass` and `ObjCProtocol`

My additional questions are:
- Python ids and pointer addresses are mixed. Is this right? Is it necessary to unify either, or provide a way to recognize which is displayed? (For example: `at` before id and nothing before address. Or, `&` before address.)
- Doesn't the `ObjCMethod` need id or address?
- Should the representation of `Block` be also customized?

**Comment by freakboy3742** [comment]
> * Python ids and pointer addresses are mixed. Is this right? Is it necessary to unify either, or provide a way to recognize which is displayed? (For example: `at` before id and nothing before address. Or, `&` before address.)

Broadly I think we should stick to Python IDs, but I wouldn't get *too* concerned if an ObjC memory address leaks in via DebugDescription or similar.

> * Doesn't the `ObjCMethod` need id or address?

I don't think so - a normal end user needs to know they've got a handle to a method, and the encoding that method expects; the specific pointer in memory to the method instance will only really help people working *on* Rubicon.

> * Should the representation of `Block` be also customized?

That seems reasonable to me.
