### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by freakboy3742** [beeware/rubicon-objc#66]
At some point, a v1.0 release is inevitable. What features do we need to add before we formalise APIs and push the big One Oh?

**Comment by dgelessus** [comment]
GitHub has a "milestones" feature for this sort of thing. Let's see if I can figure out how to use it...

**Comment by dgelessus** [comment]
OK, I'm creating a couple of issues for things that I think we should have at some point, not all necessarily for a 1.0 release. Documentation (#67) is IMHO a requirement, so that's the only thing I added to the v1.0 milestone right now, but feel free to add other issues if you think they should be done for 1.0.

**Comment by freakboy3742** [comment]
I'm going to close this ticket; A milestone is a better way to track this.
